# Generated by Django 3.0.7 on 2021-03-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiJiPage', '0006_auto_20210314_0756'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='identity',
            field=models.CharField(choices=[('LianXiSheng', '练习生'), ('TechDep', '技术部门')], default='LianXiSheng', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_Image',
            field=models.ImageField(default='default_profile.jpg', upload_to='profile_pics'),
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
